language: node_js
node_js:
  - "node"
install:
  - npm install
  - npm install -g codecov
  - npm install -g nyc
script:
  - nyc npm test
  - nyc report --reporter=text-lcov > coverage.lcov
  - codecov
branches:
  only:
  - master
  - develop